apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: dapr-trafficcontrol
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
        - name: simulation
          image: ghcr.io/ondfisk/simulation:latest
          imagePullPolicy: Always
          env:
            - name: TRAFFIC_CONTROL_ENDPOINT
              value: http://trafficcontrolservice:6001
          ports:
            - containerPort: 6004
