apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailserver
    version: v1
  name: mailserver
  namespace: dapr-trafficcontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
      version: v1
  template:
    metadata:
      labels:
        app: mailserver
        version: v1
    spec:
      containers:
        - image: maildev/maildev:2.0.5
          imagePullPolicy: IfNotPresent
          name: mailserver
          ports:
            - containerPort: 1025
            - containerPort: 1080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailserver
    version: v1
  name: mailserver
  namespace: dapr-trafficcontrol
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 1080
      targetPort: 1080
      protocol: TCP
    - name: smtp
      port: 1025
      targetPort: 1025
      protocol: TCP
  selector:
    app: mailserver
