---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dapr-trafficcontrol
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
    - name: region
      value: eu-north-1
    - name: accessKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: accessKey
      value: ""
    - name: secretKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: secretKey
scopes:
  - trafficcontrolservice
  - finecollectionservice
