---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: eu-north-1
    - name: accessKey
      value: "[aws_access_key]"
    - name: secretKey
      value: "[aws_secret_key]"
    - name: sessionToken
      value: "[aws_session_token]"
scopes:
  - trafficcontrolservice
  - finecollectionservice
