---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: eu-north-1
    - name: accessKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: access_key
    - name: secretKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: secret_key
scopes:
  - trafficcontrolservice
  - finecollectionservice
