---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-trafficcontrol
spec:
  type: state.redis
  version: v1
  metadata:
    - name: region
      value: eu-north-1
    - name: table
      value: vehicles
    - name: accessKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: accessKey
      value: ""
    - name: secretKey
      secretKeyRef:
        name: trafficcontrol-secrets
        key: secretKey
auth:
  secretStore: secretstore
scopes:
  - trafficcontrolservice
