---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
  - trafficcontrolservice
  - finecollectionservice
